# ~/.vim/userautoload/dein/plugins_lazy.toml

[[plugins]]
repo = 'Shougo/dein.vim'

[[plugins]]
repo = 'Shougo/neocomplete.vim'
hook_add = 'source ~/.vim/userautoload/plugins/plugins-neocomplete.vim'

[[plugins]]
repo = 'Shougo/unite.vim'

[[plugins]]
repo = 'scrooloose/syntastic'
hook_add = 'source ~/.vim/userautoload/plugins/plugins-syntastic.vim'

#メモ帳
[[plugins]]
repo = 'glidenote/memolist.vim'
hook_add = 'source ~/.vim/userautoload/plugins/plugins-memolist.vim'

#vimからブラウザを開く
[[plugins]]
repo = 'tyru/open-browser.vim'

[[plugins]]
repo = 'thinca/vim-singleton'
hook_add = 'source ~/.vim/userautoload/plugins/plugins-singleton.vim'

#vimhelpの日本語
[[plugins]]
repo = 'vim-jp/vimdoc-ja'
