[[plugins]]
repo = 'Shougo/dein.vim'

[[plugins]]
repo = 'Shougo/neocomplete.vim'
hook_add = 'source ~/.vim/userautoload/plugins/plugins-neocomplete.vim'

[[plugins]]
repo = 'Shougo/unite.vim'

[[plugins]]
repo = 'scrooloose/syntastic'
hook_add = 'source ~/.vim/userautoload/plugins/plugins-syntastic.vim'

[[plugins]]
repo = 'mattn/emmet-vim'
hook_add = 'source ~/.vim/userautoload/plugins/plugins-emmet.vim'

#メモ帳
[[plugins]]
repo = 'glidenote/memolist.vim'
hook_add = 'source ~/.vim/userautoload/plugins/plugins-memolist.vim'

#vimhelpの日本語
[[plugins]]
repo = 'vim-jp/vimdoc-ja'

#TOMLファイルのハイライトシンタックス
[[plugins]]
repo = 'cespare/vim-toml'

[[plugins]]
repo = 'thinca/vim-singleton'
hook_add = 'source ~/.vim/userautoload/plugins/plugins-singleton.vim'
